using Content.Client.UserInterface.Systems.Inventory;
using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.Controls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Combat.Widgets;

[GenerateTypedNameReferences]
public sealed partial class CombatGui : UIWidget
{
    public CombatGui()
    {
        RobustXamlLoader.Load(this);

        LayoutContainer.SetGrowVertical(this, LayoutContainer.GrowDirection.Begin);
    }
}
