using Robust.Client.AutoGenerated;
using Robust.Client.UserInterface.CustomControls;
using Robust.Client.UserInterface.XAML;

namespace Content.Client.UserInterface.Systems.Objectives.Windows;

[GenerateTypedNameReferences]
public sealed partial class JobObjectivesWindow : DefaultWindow
{
    public JobObjectivesWindow()
    {
        RobustXamlLoader.Load(this);
    }
}
